import type { Destination, Package, Testimonial, Vendor, Booking, Notification } from '@/types';

export const DEMO_ACCOUNTS = [
  {
    role: 'traveler' as const,
    email: 'traveler@fingertrip.com',
    password: 'Traveler@123',
    name: 'Alex Johnson',
    label: 'Traveler Demo',
    description: 'Explore bookings, wishlist & payments',
    color: 'from-orange-500 to-amber-500',
    icon: '🧳',
  },
  {
    role: 'vendor' as const,
    email: 'vendor@fingertrip.com',
    password: 'Vendor@123',
    name: 'Sunrise Travels Co.',
    label: 'Vendor Demo',
    description: 'Manage packages, orders & earnings',
    color: 'from-emerald-500 to-teal-500',
    icon: '🏢',
  },
  {
    role: 'admin' as const,
    email: 'admin@fingertrip.com',
    password: 'Admin@123',
    name: 'FingerTrip Admin',
    label: 'Admin Demo',
    description: 'Full platform access & analytics',
    color: 'from-purple-500 to-indigo-500',
    icon: '⚙️',
  },
];

export const DESTINATIONS: Destination[] = [
  {
    id: '1',
    name: 'Bali',
    country: 'Indonesia',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80',
    price: 1299,
    rating: 4.9,
    reviews: 2847,
    description: 'Tropical paradise with lush rice terraces, ancient temples, and pristine beaches.',
    tags: ['Beach', 'Culture', 'Luxury'],
    popular: true,
  },
  {
    id: '2',
    name: 'Switzerland',
    country: 'Europe',
    image: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=600&q=80',
    price: 3499,
    rating: 4.8,
    reviews: 1923,
    description: 'Breathtaking alpine scenery, pristine lakes, and charming medieval villages.',
    tags: ['Mountains', 'Adventure', 'Premium'],
    popular: true,
  },
  {
    id: '3',
    name: 'Kashmir',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=600&q=80',
    price: 899,
    rating: 4.9,
    reviews: 3156,
    description: 'Heaven on Earth — Dal Lake houseboats, Mughal gardens, and snow-capped peaks.',
    tags: ['Mountains', 'Culture', 'Nature'],
    popular: true,
  },
  {
    id: '4',
    name: 'Dubai',
    country: 'UAE',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80',
    price: 2199,
    rating: 4.7,
    reviews: 4230,
    description: 'Futuristic skyline, luxury shopping, desert adventures, and world-class dining.',
    tags: ['Luxury', 'City', 'Shopping'],
    popular: true,
  },
  {
    id: '5',
    name: 'Thailand',
    country: 'Southeast Asia',
    image: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=600&q=80',
    price: 1099,
    rating: 4.8,
    reviews: 5102,
    description: 'Temples, street food, turquoise beaches, and vibrant nightlife.',
    tags: ['Culture', 'Beach', 'Food'],
    popular: true,
  },
  {
    id: '6',
    name: 'Goa',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&q=80',
    price: 699,
    rating: 4.6,
    reviews: 6781,
    description: "India's beach capital — golden sands, colonial churches, and vibrant beach parties.",
    tags: ['Beach', 'Party', 'Culture'],
    popular: false,
  },
];

export const PACKAGES: Package[] = [
  {
    id: '1',
    title: 'Maldives Luxury Escape',
    destination: 'Maldives',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=600&q=80',
    price: 4999,
    originalPrice: 6499,
    duration: '7 Days / 6 Nights',
    rating: 4.9,
    reviews: 342,
    vendor: 'Azure Horizons Travel',
    description: 'Stay in overwater bungalows with private pools, snorkeling with manta rays, and world-class dining.',
    itinerary: ['Day 1: Arrival & Resort Check-in', 'Day 2: Water Activities & Snorkeling', 'Day 3: Island Hopping', 'Day 4: Spa & Relaxation', 'Day 5: Sunset Cruise', 'Day 6: Free Day', 'Day 7: Departure'],
    includes: ['Round-trip flights', 'Overwater villa', 'All meals', 'Water sports', 'Airport transfer'],
    discount: 23,
    trending: true,
    category: 'Luxury',
  },
  {
    id: '2',
    title: 'Swiss Alps Adventure',
    destination: 'Switzerland',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    price: 5499,
    originalPrice: 6999,
    duration: '10 Days / 9 Nights',
    rating: 4.8,
    reviews: 218,
    vendor: 'Alpine Dreams Tours',
    description: 'Ski the Jungfrau, cruise Lake Geneva, explore Lucerne and Zurich in ultimate Alpine luxury.',
    itinerary: ['Day 1: Arrive Zurich', 'Day 2: Lucerne Day Trip', 'Day 3: Jungfrau Region', 'Day 4-5: Skiing & Activities', 'Day 6: Geneva', 'Day 7: Lake Cruise', 'Day 8-9: Interlaken', 'Day 10: Departure'],
    includes: ['Flights', '5-star hotels', 'Swiss Rail Pass', 'Guided tours', 'Breakfast & dinner'],
    discount: 21,
    trending: true,
    category: 'Adventure',
  },
  {
    id: '3',
    title: 'Kashmir Paradise Tour',
    destination: 'Kashmir',
    image: 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=600&q=80',
    price: 1299,
    originalPrice: 1699,
    duration: '6 Days / 5 Nights',
    rating: 4.9,
    reviews: 891,
    vendor: 'Himalayan Trails Co.',
    description: 'Dal Lake houseboat stay, Gulmarg snowfall, Pahalgam meadows, and authentic Kashmiri cuisine.',
    itinerary: ['Day 1: Arrive Srinagar', 'Day 2: Dal Lake Shikara', 'Day 3: Gulmarg', 'Day 4: Pahalgam', 'Day 5: Mughal Gardens', 'Day 6: Departure'],
    includes: ['Flights', 'Houseboat & hotel', 'All meals', 'Shikara rides', 'Guided tours'],
    discount: 24,
    trending: true,
    category: 'Nature',
  },
  {
    id: '4',
    title: 'Dubai Premium Experience',
    destination: 'Dubai',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80',
    price: 2799,
    originalPrice: 3499,
    duration: '5 Days / 4 Nights',
    rating: 4.7,
    reviews: 567,
    vendor: 'Desert Pearl Journeys',
    description: 'Burj Khalifa, desert safari, Atlantis Aquaventure, Dubai Mall, and luxury hotel stay.',
    itinerary: ['Day 1: Arrive & City Tour', 'Day 2: Burj Khalifa & Mall', 'Day 3: Desert Safari', 'Day 4: Atlantis & Beach', 'Day 5: Shopping & Departure'],
    includes: ['Flights', '5-star hotel', 'Desert safari', 'City tours', 'Breakfast'],
    discount: 20,
    trending: false,
    category: 'Luxury',
  },
  {
    id: '5',
    title: 'Bali Spiritual Retreat',
    destination: 'Bali',
    image: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=600&q=80',
    price: 1899,
    originalPrice: 2499,
    duration: '8 Days / 7 Nights',
    rating: 4.8,
    reviews: 743,
    vendor: 'Sunrise Travels Co.',
    description: 'Yoga retreats in Ubud, temple ceremonies, rice terrace treks, and world-class spa treatments.',
    itinerary: ['Day 1: Arrive Bali', 'Day 2: Ubud & Monkey Forest', 'Day 3: Yoga & Spa', 'Day 4: Rice Terrace Trek', 'Day 5: Temple Tour', 'Day 6: Beach & Surfing', 'Day 7: Cooking Class', 'Day 8: Departure'],
    includes: ['Flights', 'Villa accommodation', 'Daily breakfast', 'Yoga sessions', 'Temple tours'],
    discount: 24,
    trending: true,
    category: 'Wellness',
  },
  {
    id: '6',
    title: 'Thailand Island Hopping',
    destination: 'Thailand',
    image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=600&q=80',
    price: 1599,
    originalPrice: 2099,
    duration: '9 Days / 8 Nights',
    rating: 4.7,
    reviews: 1024,
    vendor: 'Thai Discovery Tours',
    description: 'Bangkok street food, Phi Phi Islands, Chiang Mai temples, and Phuket luxury beach clubs.',
    itinerary: ['Day 1-2: Bangkok', 'Day 3: Chiang Mai', 'Day 4: Temples & Markets', 'Day 5: Fly to Phuket', 'Day 6: Phi Phi Islands', 'Day 7: Beach Day', 'Day 8: Island Sunset', 'Day 9: Departure'],
    includes: ['Flights', 'Hotels & resorts', 'Island ferry', 'Food tours', 'Guided tours'],
    discount: 24,
    trending: true,
    category: 'Adventure',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Mitchell',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
    location: 'New York, USA',
    rating: 5,
    comment: 'FingerTrip made our Maldives honeymoon absolutely perfect. Every detail was flawlessly arranged — from the overwater villa to the sunset cruise. Worth every penny!',
    package: 'Maldives Luxury Escape',
    date: 'March 2026',
  },
  {
    id: '2',
    name: 'Rajesh Kumar',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    location: 'Mumbai, India',
    rating: 5,
    comment: 'The Kashmir tour was beyond imagination. Our guide was exceptional, the houseboat was magical, and the Gulmarg snow experience was surreal. Highly recommended!',
    package: 'Kashmir Paradise Tour',
    date: 'February 2026',
  },
  {
    id: '3',
    name: 'Emma Williams',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
    location: 'London, UK',
    rating: 5,
    comment: 'Swiss Alps trip organized by FingerTrip was extraordinary! The hotel selections, rail pass, and guided excursions — everything was premium. Already planning my next trip!',
    package: 'Swiss Alps Adventure',
    date: 'January 2026',
  },
  {
    id: '4',
    name: 'Kenji Tanaka',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
    location: 'Tokyo, Japan',
    rating: 5,
    comment: "Dubai exceeded all expectations! The desert safari was exhilarating and the Burj Khalifa dinner was unforgettable. FingerTrip's premium service stood out throughout.",
    package: 'Dubai Premium Experience',
    date: 'December 2025',
  },
  {
    id: '5',
    name: 'Priya Sharma',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80',
    location: 'Bangalore, India',
    rating: 5,
    comment: "The Bali retreat was exactly what I needed. Yoga sessions, temple visits, and the most relaxing spa — FingerTrip curated it all beautifully. Can't wait to go back!",
    package: 'Bali Spiritual Retreat',
    date: 'November 2025',
  },
];

export const VENDORS: Vendor[] = [
  {
    id: '1',
    name: 'Azure Horizons Travel',
    logo: 'https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?w=100&q=80',
    location: 'Maldives & Bali',
    packages: 24,
    rating: 4.9,
    reviews: 1842,
    verified: true,
    specialties: ['Luxury Beach', 'Overwater Villas', 'Diving'],
    description: 'Specialists in luxury island experiences with premium overwater accommodations across the Indian Ocean.',
  },
  {
    id: '2',
    name: 'Alpine Dreams Tours',
    logo: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=100&q=80',
    location: 'Europe',
    packages: 18,
    rating: 4.8,
    reviews: 1243,
    verified: true,
    specialties: ['Alpine Adventures', 'Ski Tours', 'Cultural Tours'],
    description: 'European travel experts offering curated Swiss, French, and Italian luxury experiences.',
  },
  {
    id: '3',
    name: 'Himalayan Trails Co.',
    logo: 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=100&q=80',
    location: 'India',
    packages: 32,
    rating: 4.9,
    reviews: 3421,
    verified: true,
    specialties: ['Kashmir', 'Himachal', 'Ladakh', 'Uttarakhand'],
    description: "India's most trusted mountain travel experts with 15+ years crafting Himalayan experiences.",
  },
  {
    id: '4',
    name: 'Desert Pearl Journeys',
    logo: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=100&q=80',
    location: 'UAE & Middle East',
    packages: 15,
    rating: 4.7,
    reviews: 987,
    verified: true,
    specialties: ['Dubai Luxury', 'Desert Safari', 'Cultural Tours'],
    description: 'Premium Middle Eastern experiences with five-star accommodations and private desert adventures.',
  },
  {
    id: '5',
    name: 'Sunrise Travels Co.',
    logo: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=100&q=80',
    location: 'Bali & Thailand',
    packages: 28,
    rating: 4.8,
    reviews: 2156,
    verified: true,
    specialties: ['Wellness Retreats', 'Island Hopping', 'Spiritual Tours'],
    description: 'Southeast Asia specialists crafting transformative wellness and adventure travel experiences.',
  },
  {
    id: '6',
    name: 'Thai Discovery Tours',
    logo: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=100&q=80',
    location: 'Thailand',
    packages: 21,
    rating: 4.7,
    reviews: 1789,
    verified: true,
    specialties: ['Island Hopping', 'Street Food Tours', 'Temple Visits'],
    description: 'Authentic Thai experiences from Bangkok street food to Phi Phi island luxury resorts.',
  },
];

export const TRAVELER_BOOKINGS: Booking[] = [
  {
    id: 'BK001',
    packageTitle: 'Maldives Luxury Escape',
    destination: 'Maldives',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=200&q=80',
    date: '2026-06-15',
    travelers: 2,
    amount: 9998,
    status: 'confirmed',
    vendor: 'Azure Horizons Travel',
  },
  {
    id: 'BK002',
    packageTitle: 'Bali Spiritual Retreat',
    destination: 'Bali',
    image: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=200&q=80',
    date: '2026-03-10',
    travelers: 1,
    amount: 1899,
    status: 'completed',
    vendor: 'Sunrise Travels Co.',
  },
  {
    id: 'BK003',
    packageTitle: 'Kashmir Paradise Tour',
    destination: 'Kashmir',
    image: 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=200&q=80',
    date: '2026-08-20',
    travelers: 4,
    amount: 5196,
    status: 'pending',
    vendor: 'Himalayan Trails Co.',
  },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: '1',
    title: 'Booking Confirmed!',
    message: 'Your Maldives Luxury Escape booking has been confirmed. Get ready for paradise!',
    type: 'success',
    read: false,
    date: '2026-04-07',
  },
  {
    id: '2',
    title: 'Special Offer',
    message: 'Get 30% off on Swiss Alps Adventure — limited seats available!',
    type: 'info',
    read: false,
    date: '2026-04-06',
  },
  {
    id: '3',
    title: 'Payment Received',
    message: 'Payment of $9,998 for Maldives package received successfully.',
    type: 'success',
    read: true,
    date: '2026-04-05',
  },
  {
    id: '4',
    title: 'Trip Reminder',
    message: 'Your Maldives trip is 68 days away. Check your travel documents!',
    type: 'warning',
    read: true,
    date: '2026-04-04',
  },
];
